"""add email_verified_at to users

Revision ID: 88c46d82cbe3
Revises: 417a35d561a0
Create Date: 2026-09-12 13:42:56.597460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2  # noqa: F401 - required for autogenerated Geometry() column defs


# revision identifiers, used by Alembic.
revision: str = '88c46d82cbe3'
down_revision: Union[str, Sequence[str], None] = '417a35d561a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###
